clock_period: 5ns
#custom_taxo_to_model_mapping:
#  buffers:
#  - name: buffer_id
#    format_interfaces:
#    - dataspace: A
#      index: 0
#      anchor: True
#      constraints:
#      - asdf
scale_inference_include_obj:
  energy: null
  area: null
scale_inference_solver:
  manager: neos
  solver: filmint
  args:
    neos_email: abf149@mit.edu
model_export_settings:
  accelergy_version: 0.3
  component_single_file: True