clock_period: 5ns
scale_inference_include_obj:
  energy: null
  area: null
scale_inference_solver:
  manager: neos
  solver: filmint
  args:
    neos_email: abf149@mit.edu
model_export_settings:
  accelergy_version: 0.3
  component_single_file: True