safsearch:
  force_attribute_ranges:
  - uri: /.Skipping_iact_spad1_weight_spad0
    settings:
    - type: positional
      effect: allow
      ranges:
      - position: 3
        range: ['none']
    - type: positional
      effect: deny
      ranges:
      - position: 4
        range: ['none','lut']
safinfer:
  force_attributes:
  #- uri: /.Skipping_iact_spad1_weight_spad0
  #  settings:
  #  - type: positional
  #    values:
  #    - position: 3
  #      value: 'none'
  #    - position: 4
  #      value: 'none'
safmodel:
  clock_period: 5ns
  scale_inference_include_obj:
    energy: null
    area: null
  scale_inference_solver:
    manager: neos
    solver: filmint
    args:
      neos_email: abf149@mit.edu
  model_export_settings:
    accelergy_version: 0.3
    component_single_file: True