clock_period: 5ns
dataspaces:
  read_write_dataspace_id: Outputs
custom_taxonomic_specifications:
  dense_buffer_format_interfaces:
  - name: psum_spad
    dataspaces:
    - name: Outputs
      dummy_format_interfaces:
      - flattened-rankIDs: [ [ C ] ]
#      - flattened-rankIDs: [ [ M ] ] 
custom_taxo_to_model_settings: []
#   - type: buffer
#     settings:
#     - name: iact_spad
#       settings:
#       - type: format_interfaces
#         settings:
#         - dataspace: Inputs
#           index: 0
#           settings:
#             - name: anchor
#               value: True
#         - dataspace: Inputs
#           index: 1
#           settings:
#             - name: anchor
#               value: False
#     - name: weight_spad
#       settings:
#       - type: format_interfaces
#         settings:
#         - dataspace: Weights
#           index: 1
#           settings:
#             - name: anchor
#               value: False
# #custom_model_specifications:
scale_inference_include_obj:
  energy: null
  area: null
scale_inference_solver:
  manager: neos
  solver: filmint
  args:
    neos_email: abf149@mit.edu
model_export_settings:
  accelergy_version: 0.3
  component_single_file: True
  library_search_paths:
  - :base