'''Modelscript components keywords'''
import script_parser.model_parser_support.primitive.primitive_keywords as pkw_

modelscript_components='modelscript_components'

component_name=pkw_.primitive_name
from_taxonomic_component="from_taxonomic_component"
taxo_component_description=pkw_.taxo_primitive_description
taxo_component_instances=pkw_.taxo_primitive_instances
component_scale_parameters=pkw_.primitive_scale_parameters